### ISSUE TITLE
你好 

### ISSUE THREAD

**Issue by MRKINKI** [magicdict/FDDC#1]

**Comment by freeopen** [comment]
赛1 还是 赛2




| |
freeopen
邮箱：freeopen@163.com
|

签名由 网易邮箱大师 定制

在2018年07月12日 20:23，MRKINKI 写道：

因为我发现这个比赛比较晚 已经无法下载初赛数据 但本人对此项目非常感兴趣 希望能使用该数据做一些实验 请问可以分享一份数据给我吗？

**Comment by MRKINKI** [comment]
谢谢您的回复 我就是钉钉那个强迫症(私信您要抽取那个) 祝您比赛顺利





在 2018-07-13 18:43:02，"freeopen" <notifications@github.com> 写道：
赛1 还是 赛2




| |
freeopen
邮箱：freeopen@163.com
|

签名由 网易邮箱大师 定制

在2018年07月12日 20:23，MRKINKI 写道：

因为我发现这个比赛比较晚 已经无法下载初赛数据 但本人对此项目非常感兴趣 希望能使用该数据做一些实验 请问可以分享一份数据给我吗？

**Comment by magicdict** [comment]
通过邮件发送了。
