### ISSUE TITLE
能否提供部分代码中使用到的数据

### ISSUE THREAD

**Issue by qiangchong2017** [magicdict/FDDC#2]
Hi,您好!
     经过阅读源代码，有需求会用到这部分功能，可否提供源代码中使用到的部分数据，方便验证与调试呢，谢谢！

**Comment by magicdict** [comment]
这个是天池比赛的题目。如果需要的话，可以去天池竞赛下载，数据量实在太大了（20G数据。）

**Comment by qiangchong2017** [comment]
20G确实太大了，可否提供资产重组，增减持，定增这三部分的数据量，每个2MB或2KB也可以的，谢谢！若你方便的话可以QQ联系我：2092730044
